name: flutube
description: Youtube video downloader made using flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bot_toast: ^4.0.1
  cached_network_image: ^3.0.0
  connectivity_plus: ^1.1.0
  custom_text: ^0.5.0
  # dart_vlc: ^0.1.7
  dio: ^4.0.0
  equatable: ^2.0.3
  file_picker: ^4.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_staggered_grid_view: ^0.4.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hooks_riverpod: ^1.0.0-dev.7
  intl: ^0.17.0
  lucide_icons: ^0.15.30
  # Upgrade to pub.dev when package > 3.2.1
  open_file:
    git:
      url: https://github.com/miDeb/open_file.git
      ref: no_system
  package_info_plus: ^1.0.6
  path: ^1.8.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.2
  readmore: ^2.1.0
  salomon_bottom_bar: ^3.1.0
  share_plus: ^2.1.4
  shared_preferences: ^2.0.7
  sticky_headers: ^0.2.0
  timeago: ^3.1.0
  url_launcher: ^6.0.11
  youtube_explode_dart: ^1.10.7-dev.1

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^1.0.4
  hive_generator: ^1.1.1

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          style: italic
          weight: 900
