name: pstube
description: Watch and download videos without ads

publish_to: none
version: 2.6.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  adwaita: ^0.5.1
  audio_video_progress_bar: ^0.11.0
  bot_toast:
    git:
      url: https://github.com/MMMzq/bot_toast.git
  built_collection: ^5.1.1
  cached_network_image: ^3.2.0
  connectivity_plus: ^3.0.2
  custom_text: ^0.6.0-dev.1
  dart_vlc: ^0.4.0
    # git:
    #   url: https://github.com/alexmercerind/dart_vlc
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  equatable: ^2.0.3 
  file_picker: ^5.2.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2+1
  flutter_html: ^3.0.0-alpha.5
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.0.0-dev.0
  html: ^0.15.0
  intl: ^0.17.0
  libadwaita:
    git:
      url: https://github.com/gtk-flutter/libadwaita
      ref: native-controls
  libadwaita_searchbar_ac: ^0.5.8
  libadwaita_window_manager: ^0.5.4
  lucide_icons: ^0.104.0
  open_file: # Upgrade to pub.dev when package > 3.2.1
    git:
      url: https://github.com/miDeb/open_file.git
      ref: no_system
  package_info_plus: ^1.3.0
  page_transition: ^2.0.5
  path: ^1.8.0
  path_provider: ^2.0.8
  permission_handler: ^10.0.0
  piped_api:
    git:
      url: https://github.com/TeamPiped/piped_dart
  pod_player: ^0.1.0
  readmore: ^2.1.0
  responsive_framework: ^0.2.0
  share_plus: ^6.3.0
  shared_preferences: ^2.0.13
  sticky_headers: ^0.3.0+2
  timeago: ^3.2.1
  url_launcher: ^6.0.18
  window_manager: ^0.2.6
  youtube_explode_dart: ^1.12.0

dev_dependencies:
  build_runner: ^2.1.11
  hive_generator: ^2.0.0
  msix: ^3.6.2
  very_good_analysis: ^3.0.0

dependency_overrides:
  ffi: ^2.0.1
#   window_manager:
#     git:
#       url: https://github.com/prateekmedia/window_manager
#       ref: patch-1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans/NotoSans-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans/NotoSans-BoldItalic.ttf
          style: italic
          weight: 700

msix_config:
  display_name: PsTube
  publisher_display_name: Prateek Sunal
  identity_name: com.prateekmedia.pstube
  msix_version: 2.0.0
  capabilities: "internetClient"
  store: false
