name: pstube
description: Watch and download videos without ads

publish_to: none
version: 3.0.0+3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  adwaita: ^1.0.1
  audio_video_progress_bar: ^1.0.1
  bot_toast:
    git:
      url: https://github.com/MMMzq/bot_toast.git
  built_collection: ^5.1.1
  cached_network_image: ^3.2.0
  connectivity_plus: ^4.0.1
  custom_text: ^1.0.0
  # dart_vlc:
  # git:
  #   url: https://github.com/alexmercerind/dart_vlc
  dio: ^5.0.0
  dio_cookie_manager: ^3.1.0
  equatable: ^2.0.3
  file_picker: ^5.2.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2+1
  flutter_html: ^3.0.0-beta.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.6
  html: ^0.15.0
  http: ^0.13.6
  intl: ^0.18.0
  libadwaita: ^2.0.1
  libadwaita_searchbar_ac: ^0.5.8
  libadwaita_window_manager: ^0.5.4
  lucide_icons: ^0.241.0
  media_kit:
  # git:
  #   url: https://github.com/zezo357/media_kit
  #   ref: controls
  #   path: media_kit
  media_kit_libs_linux:
  media_kit_libs_windows_video:
  media_kit_native_event_loop:
  media_kit_video:
  media_kit_video_controls:
    git:
      url: https://github.com/prateekmedia/media_kit
      ref: controls
      path: media_kit_video_controls
  open_filex: ^4.3.0
  package_info_plus: ^4.0.2
  page_transition: ^2.0.5
  parsed_readmore: ^0.0.6
  path: ^1.8.0
  path_provider: ^2.0.8
  permission_handler: ^10.0.0
  piped_api:
    git:
      url: https://github.com/TeamPiped/piped_dart
  pod_player: ^0.1.0
  responsive_framework: ^1.0.0
  share_plus: ^7.0.2
  shared_preferences: ^2.0.13
  sticky_headers: ^0.3.0+2
  timeago: ^3.2.1
  url_launcher: ^6.0.18
  window_manager: ^0.3.2
  youtube_explode_dart: ^1.12.3

dev_dependencies:
  build_runner: ^2.1.11
  hive_generator: ^2.0.0
  msix: ^3.6.2
  very_good_analysis: ^5.0.0+1

dependency_overrides:
  csslib: 0.17.0
  ffi: ^2.0.1
#   window_manager:
#     git:
#       url: https://github.com/prateekmedia/window_manager
#       ref: patch-1
  wakelock: ^0.6.2
  wakelock_windows: ^0.2.1
  win32: ^4.0.0
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans/NotoSans-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans/NotoSans-BoldItalic.ttf
          style: italic
          weight: 700

msix_config:
  display_name: PsTube
  publisher_display_name: Prateek Sunal
  identity_name: com.prateekmedia.pstube
  msix_version: 2.0.0
  capabilities: "internetClient"
  store: false
